name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use the GitHub token
        run: |
          echo "Accessing the token from GitHub secrets"
          echo "The token is: ${{ secrets.TOKEN }}"
