[theme]
primaryColor="#67aeaa"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#FFFFFF"
textColor="#323e47"
[client]
showSidebarNavigation = false
[server]
headless = true
enableCORS = false
enableWebsocketCompression = false
port = 8501
enableXsrfProtection = false
address = "0.0.0.0"
